{% set name = "CTDFjorder" %}
  {% set version = "0.0.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 141d3f300662347c177d06b06d2d5f4c83ff56b6776160e722b6d95357a71072

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - numpy >=1.26.4
    - pandas >=2.2.1
    - gsw >=3.6.17
    - matplotlib >=3.8.4
    - statsmodels >=0.14.0
    - tabulate >=0.9.0
    - pyrsktools ==0.1.9
    - openpyxl >=3.1.2

test:
  imports:
    - CTDFjorder
  commands:
    - ctdfjorder-cli --help

about:
  home: https://github.com/nikothomas/CTDFjorder
  license: MIT
  license_file: LICENSE
  summary: A package for processing and analyzing CTD data.

extra:
  recipe-maintainers:
    - nikothomas